/** Local city -> country lookup for the Destinationer tab. No external API calls. */
const CITY_COUNTRY: Record<string, string> = {
  stockholm: "Sverige",
  göteborg: "Sverige",
  gothenburg: "Sverige",
  malmö: "Sverige",
  luleå: "Sverige",
  umeå: "Sverige",
  östersund: "Sverige",
  visby: "Sverige",
  ronneby: "Sverige",
  kiruna: "Sverige",
  "kiruna airport": "Sverige",
  sundsvall: "Sverige",
  skellefteå: "Sverige",
  kalmar: "Sverige",
  växjö: "Sverige",
  ängelholm: "Sverige",
  karlstad: "Sverige",
  örnsköldsvik: "Sverige",
  köpenhamn: "Danmark",
  copenhagen: "Danmark",
  billund: "Danmark",
  aalborg: "Danmark",
  oslo: "Norge",
  bergen: "Norge",
  trondheim: "Norge",
  stavanger: "Norge",
  helsingfors: "Finland",
  helsinki: "Finland",
  reykjavik: "Island",
  keflavik: "Island",
  london: "Storbritannien",
  manchester: "Storbritannien",
  edinburgh: "Storbritannien",
  dublin: "Irland",
  amsterdam: "Nederländerna",
  bryssel: "Belgien",
  brussels: "Belgien",
  paris: "Frankrike",
  nice: "Frankrike",
  frankfurt: "Tyskland",
  münchen: "Tyskland",
  munich: "Tyskland",
  berlin: "Tyskland",
  düsseldorf: "Tyskland",
  hamburg: "Tyskland",
  zürich: "Schweiz",
  zurich: "Schweiz",
  genève: "Schweiz",
  geneva: "Schweiz",
  wien: "Österrike",
  vienna: "Österrike",
  warszawa: "Polen",
  warsaw: "Polen",
  gdansk: "Polen",
  krakow: "Polen",
  prag: "Tjeckien",
  prague: "Tjeckien",
  budapest: "Ungern",
  riga: "Lettland",
  vilnius: "Litauen",
  tallinn: "Estland",
  madrid: "Spanien",
  barcelona: "Spanien",
  "palma de mallorca": "Spanien",
  malaga: "Spanien",
  málaga: "Spanien",
  alicante: "Spanien",
  "las palmas": "Spanien",
  teneriffa: "Spanien",
  tenerife: "Spanien",
  lissabon: "Portugal",
  lisbon: "Portugal",
  faro: "Portugal",
  funchal: "Portugal",
  rom: "Italien",
  rome: "Italien",
  milano: "Italien",
  milan: "Italien",
  venedig: "Italien",
  neapel: "Italien",
  aten: "Grekland",
  athens: "Grekland",
  kreta: "Grekland",
  rhodos: "Grekland",
  istanbul: "Turkiet",
  antalya: "Turkiet",
  dubai: "Förenade Arabemiraten",
  doha: "Qatar",
  "new york": "USA",
  newark: "USA",
  chicago: "USA",
  miami: "USA",
  toronto: "Kanada",
  bangkok: "Thailand",
  phuket: "Thailand",
  "hong kong": "Hongkong",
  singapore: "Singapore",
  tokyo: "Japan",
  peking: "Kina",
  beijing: "Kina",
  shanghai: "Kina",
  delhi: "Indien",
  "tel aviv": "Israel",
  kairo: "Egypten",
  hurghada: "Egypten",
  "sharm el sheikh": "Egypten",
  marrakech: "Marocko",
  agadir: "Marocko",
  zagreb: "Kroatien",
  split: "Kroatien",
  dubrovnik: "Kroatien",
  belgrad: "Serbien",
  bukarest: "Rumänien",
  sofia: "Bulgarien",
  ljubljana: "Slovenien",
  luxemburg: "Luxemburg",
};

export const UNKNOWN_COUNTRY = "Okänt land";

export function countryForCity(city: string | null | undefined): string {
  if (!city) return UNKNOWN_COUNTRY;
  return CITY_COUNTRY[city.trim().toLowerCase()] ?? UNKNOWN_COUNTRY;
}
